apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: myns
spec:
  replicas: 5
  selector:
    matchLabels:
     env: stage
  template:
    metadata:
     labels:
       env: stage
    spec:
     imagePullSecrets:
       - name: passwd-for-docker-hub
     containers:
       - name: tomcat
         image:  shivadocker7512/shivhub:prname-BUILD_NUMBER
         ports:
          - containerPort: 8080


